assets:
- asset_type: cn_fund
  attributes:
    fund_type_raw: 货币型-普通货币
  currency: CNY
  last_updated: '2026-06-05T18:10:24.747517'
  name: 天弘余额宝货币
  source: akshare_fund_em
  symbol: 000198
- asset_type: cn_fund
  attributes:
    company: 中银基金管理有限公司
    fund_type_raw: 货币型
  currency: CNY
  last_updated: '2026-06-05T18:10:14.303527'
  name: 中银如意宝货币A
  source: akshare_fund_xq
  symbol: '004502'
- asset_type: cn_fund
  attributes:
    company: 易方达基金管理有限公司
    fund_type_raw: 混合型-偏股
  currency: CNY
  last_updated: '2026-06-05T18:10:13.547847'
  name: 易方达蓝筹精选混合
  source: akshare_fund_xq
  symbol: 005827
- asset_type: cn_fund
  attributes:
    fund_type_raw: 指数型-股票
  currency: CNY
  last_updated: '2026-06-05T18:10:12.929293'
  name: 沪深300ETF华泰柏瑞
  source: akshare_fund_em
  symbol: '510300'
- asset_type: cn_stock_sh
  attributes:
    exchange: SZ
  currency: CNY
  last_updated: '2026-06-19T00:06:40.146832'
  name: 贵州茅台
  source: akshare_stock_info
  symbol: '600519'
- asset_type: us_equity
  attributes: {}
  currency: USD
  name: AAPL
  symbol: AAPL
- asset_type: currency
  attributes:
    base_currency: USD
    pair_type: unknown
    quote_currency: UNKNOWN
  currency: USD
  last_updated: '2026-05-22T03:43:51.816844'
  name: EUR/USD
  source: currency_detector
  symbol: EUR/USD
- asset_type: us_equity
  attributes: {}
  currency: USD
  name: GLD
  symbol: GLD
- asset_type: us_equity
  attributes:
    exchange: NMS
    sector: Communication Services
  currency: USD
  last_updated: '2026-02-18T00:16:40.855410'
  name: Alphabet Inc.
  source: yfinance
  symbol: GOOGL
- asset_type: us_equity
  attributes:
    exchange: NMS
    sector: Technology
  currency: USD
  last_updated: '2026-02-18T00:25:30.188533'
  name: Microsoft Corporation
  source: yfinance
  symbol: MSFT
- asset_type: us_equity
  attributes: {}
  currency: USD
  name: QQQ
  symbol: QQQ
- asset_type: us_equity
  attributes: {}
  currency: USD
  name: TLT
  symbol: TLT
- asset_type: currency
  attributes:
    base_currency: USD
    pair_type: major
    quote_currency: CAD
  currency: USD
  last_updated: '2026-02-13T21:11:15.732378'
  name: USD/CAD
  source: currency_detector
  symbol: USDCAD
- asset_type: cn_stock
  attributes:
    exchange: SH
  currency: CNY
  last_updated: '2026-05-22T03:43:51.811457'
  name: 平安银行
  source: akshare_stock_info
  symbol: sh000001
- asset_type: cn_stock
  attributes:
    exchange: SH
  currency: CNY
  last_updated: '2026-06-05T18:10:13.637710'
  name: 中国石化
  source: akshare_stock_info
  symbol: sh600028
- asset_type: cn_stock
  attributes:
    exchange: SH
  currency: CNY
  last_updated: '2026-02-13T21:11:15.725891'
  name: 贵州茅台
  source: akshare_stock_info
  symbol: sh600519
- asset_type: cn_stock
  attributes:
    exchange: SH
  currency: CNY
  last_updated: '2026-06-05T18:10:13.601514'
  name: 工商银行
  source: akshare_stock_info
  symbol: sh601398
- asset_type: cn_stock
  attributes:
    exchange: SH
  currency: CNY
  last_updated: '2026-06-05T18:10:13.619995'
  name: 紫金矿业
  source: akshare_stock_info
  symbol: sh601899
description: 资产注册表 (自动前缀+智能币种)
last_updated: '2026-06-19T00:06:40.146893'
version: '2.0'
