version: '1.0'
last_updated: '2026-06-04T16:35:18.661075'
assets:
- asset_type: cn_stock
  attributes:
    exchange: SH
  currency: CNY
  last_updated: '2026-05-22T03:43:51.811457'
  name: 平安银行
  source: akshare_stock_info
  symbol: sh000001
  asset_id: CN_STOCK:000001
- asset_type: cn_stock
  attributes:
    attributes:
      attributes:
        attributes:
          exchange: SH
  currency: CNY
  last_updated: '2026-02-13T21:11:15.725891'
  name: 贵州茅台
  source: akshare_stock_info
  symbol: sh600519
  asset_id: CN_STOCK:600519
- asset_type: currency
  attributes:
    base_currency: USD
    pair_type: unknown
    quote_currency: UNKNOWN
  currency: USD
  last_updated: '2026-05-22T03:43:51.816844'
  name: EUR/USD
  source: currency_detector
  symbol: EUR/USD
  asset_id: FX:EUR/USD
- asset_type: currency
  attributes:
    attributes:
      attributes:
        attributes:
          base_currency: USD
          pair_type: major
          quote_currency: CAD
  currency: USD
  last_updated: '2026-02-13T21:11:15.732378'
  name: USD/CAD
  source: currency_detector
  symbol: USDCAD
  asset_id: FX:USDCAD
- asset_type: us_equity
  attributes: {}
  currency: USD
  name: AAPL
  symbol: AAPL
  asset_id: US_EQ:AAPL
- asset_type: us_equity
  attributes:
    attributes:
      attributes:
        exchange: NMS
        sector: Communication Services
  currency: USD
  last_updated: '2026-02-18T00:16:40.855410'
  name: Alphabet Inc.
  source: yfinance
  symbol: GOOGL
  asset_id: US_EQ:GOOGL
- asset_type: us_equity
  attributes:
    exchange: NMS
    sector: Technology
  currency: USD
  last_updated: '2026-02-18T00:25:30.188533'
  name: Microsoft Corporation
  source: yfinance
  symbol: MSFT
  asset_id: US_EQ:MSFT
