candidates:
  assets:
  - symbol: equity.us.aapl
    asset_type: us_equity
  - symbol: equity.us.qqq
    asset_type: us_equity
  - symbol: equity.us.googl
    asset_type: us_equity
  - symbol: equity.us.gld
    asset_type: us_equity
  - symbol: equity.us.tlt
    asset_type: us_equity
  - symbol: equity.us.sgov
    asset_type: us_equity
  - symbol: fund.cn.510300
    asset_type: cn_fund
  - symbol: fund.cn.005827
    asset_type: cn_fund
  - symbol: fund.cn.002892
    asset_type: cn_fund
  - symbol: fund.cn.022459
    asset_type: cn_fund
  - symbol: fund.cn.161723
    asset_type: cn_fund
  - symbol: fund.cn.000071
    asset_type: cn_fund
  - symbol: fund.cn.019599
    asset_type: cn_fund
  - symbol: fund.cn.001235
    asset_type: cn_fund
  - symbol: fund.cn.015282
    asset_type: cn_fund
  - symbol: fund.cn.015283
    asset_type: cn_fund
  - symbol: fund.cn.004502
    asset_type: cn_fund
  - symbol: fund.cn.000198
    asset_type: cn_fund
  - symbol: fund.cn.003537
    asset_type: cn_fund
  - symbol: fund.cn.161226
    asset_type: cn_fund
  - symbol: equity.cn.sh.600519
    asset_type: cn_stock
  - symbol: equity.cn.sh.601398
    asset_type: cn_stock
  - symbol: equity.cn.sh.601899
    asset_type: cn_stock
  - symbol: equity.cn.sh.600028
    asset_type: cn_stock
  - symbol: equity.cn.sz.000001
    asset_type: cn_stock
  - symbol: equity.cn.sh.000001
    asset_type: cn_stock
